<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Pramod_Rest1" duration-ms="4118" started-at="2019-09-27T08:03:34Z" finished-at="2019-09-27T08:03:39Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="4118" started-at="2019-09-27T08:03:34Z" finished-at="2019-09-27T08:03:39Z">
      <class name="request.GetData">
        <test-method status="FAIL" signature="testbody()[pri:0, instance:request.GetData@18be83e4]" name="testbody" duration-ms="3131" started-at="2019-09-27T08:03:34Z" finished-at="2019-09-27T08:03:38Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: null
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at request.GetData.testbody(GetData.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testbody -->
      </class> <!-- request.GetData -->
      <class name="request.PostRequest">
        <test-method status="PASS" signature="createPlaceAPI()[pri:0, instance:request.PostRequest@cb5822]" name="createPlaceAPI" duration-ms="938" started-at="2019-09-27T08:03:38Z" finished-at="2019-09-27T08:03:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPlaceAPI -->
      </class> <!-- request.PostRequest -->
    </test> <!-- Test1 -->
  </suite> <!-- Pramod_Rest1 -->
</testng-results>
